### ISSUE TITLE
Problem mit useStore()

### ISSUE THREAD

**Issue by kopierschnitte** [MiRo1310/ioBroker.midas-aquatemp#7]
Erster ;-)

Beim Start der Instanz schmiert sie bei mir direkt wieder ab:

host.iobrokernano | 2024-07-11 21:53:11.418 | error | instance system.adapter.midas-aquatemp.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.iobrokernano | 2024-07-11 21:53:11.418 | error | Caught by controller[0]: Node.js v18.20.4
host.iobrokernano | 2024-07-11 21:53:11.418 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.midas-aquatemp/build/lib/store.js:24:24)
host.iobrokernano | 2024-07-11 21:53:11.418 | error | Caught by controller[0]: at require (node:internal/modules/helpers:177:18)
host.iobrokernano | 2024-07-11 21:53:11.418 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1231:19)
host.iobrokernano | 2024-07-11 21:53:11.418 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:1019:12)
host.iobrokernano | 2024-07-11 21:53:11.418 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1203:32)
host.iobrokernano | 2024-07-11 21:53:11.418 | error | Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
host.iobrokernano | 2024-07-11 21:53:11.418 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1364:14)
host.iobrokernano | 2024-07-11 21:53:11.418 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.midas-aquatemp/build/lib/saveValue.js:26:32)
host.iobrokernano | 2024-07-11 21:53:11.418 | error | Caught by controller[0]: at Object.get [as useStore] (/opt/iobroker/node_modules/iobroker.midas-aquatemp/build/lib/store.js:14:45)
host.iobrokernano | 2024-07-11 21:53:11.418 | error | Caught by controller[0]: at Object.useStore (/opt/iobroker/node_modules/iobroker.midas-aquatemp/build/lib/store.js:21:19)
host.iobrokernano | 2024-07-11 21:53:11.418 | error | Caught by controller[0]: ReferenceError: Cannot access 'useStore' before initialization
host.iobrokernano | 2024-07-11 21:53:11.418 | error | Caught by controller[0]: ^
host.iobrokernano | 2024-07-11 21:53:11.418 | error | Caught by controller[0]: useStore: () => useStore
host.iobrokernano | 2024-07-11 21:53:11.417 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.midas-aquatemp/build/lib/store.js:21

**Comment by MiRo1310** [comment]
Leider hat der erste Versuch nicht geholfen das du beheben

**Comment by MiRo1310** [comment]
Läuft jetzt
